### ISSUE TITLE
Print out dependencies that violate license rules

### ISSUE THREAD

**Issue by eidottermihi** [advanced-security/policy-as-code#27]
### Description

Currently, Policy as Code does not include the name/version of the dependencies, that violate the license rules. This makes fixing quite impossible, if you have no clue about which dependencies cause the violation.

```
Running Policy as Code...
[...]
Policy as Code
  Loading Policy as Code from Repository - https://github.com/GeekMasher/security-queries/policies/default.yml
  Cloning policy repo - GeekMasher/security-queries@main
  Loading policy file - /tmp/repo/policies/default.yml
  Policy loaded successfully
  Saving Policy...
  Policy saved
  Finished loading policy
Dependency Graph
  Total Dependency Graph :: 761
  Dependency Graph violations :: 0
Dependency Graph Results - Licensing
  Loaded extra licensing information :: 9459
  Total Dependencies in Graph :: 761
  Dependency Graph violations :: 5
Total unacceptable alerts :: 5
Error: Unacceptable Threshold of Risk has been hit!
Error: Process completed with exit code 1.
```

### Propose Solution

The output should contain the name of the dependencies that violate the rules.

**Comment by GeekMasher** [comment]
@eidottermihi You are correct, by default Policy as Code does not show the violations by default. This is due to possibly leaking information in logs.

Right now you have to add a argument to the Action:

```yml
# Policy as Code
- name: Advance Security Policy as Code
  uses: advanced-security/policy-as-code@v2.3.3
  with:
    argvs: "--display"
```

See code here:

https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/__main__.py#L52-L56

With version 3.0, the plan is that this is set in the policy file itself versus in Action.

**Comment by GeekMasher** [comment]
@eidottermihi I have moved this to discussions for now and will close this issue.

https://github.com/advanced-security/policy-as-code/discussions/33
