### ISSUE TITLE
Licensing - False positives cannot be ignored/excluded

### ISSUE THREAD

**Issue by eidottermihi** [advanced-security/policy-as-code#55]
**Describe the bug**

Licensing alerts sometimes produce false positives, for example

```
pkg:npm/escape-string-regexp@5.0.0
```

gets reported as licensed as `GPL-3.0 AND MIT`, however NPM registry tells it is plain `MIT` license (https://www.npmjs.com/package/escape-string-regexp):

![grafik](https://github.com/advanced-security/policy-as-code/assets/2780736/eff678fc-c2fd-4b46-9bf0-9f883d732147)

Therefor I'm trying to add these dependency to the `ignores` section of licensing:

```
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA
  ignores:
    ids:
      - pkg:npm/escape-string-regexp@5.0.0
```

I also tried all combinations (`ids` or `names`) with:

- `npm/escape-string-regexp`
- `escape-string-regexp`

but the dependency always shows up as a violation.

See actions here:

- https://github.com/it-at-m/appswitcher-vue/actions/runs/5711606257/job/15473520107
- https://github.com/it-at-m/appswitcher-vue/actions/runs/5711621342/job/15473563578
- https://github.com/it-at-m/appswitcher-vue/actions/runs/5711630616/job/15473590613

**To Reproduce**

Build a project with a false positive license violation and try to ignore the afflicted package/dependency.

**Expected behavior**

There should be a way to exclude such "false positives" from breaking the license check job.

**Comment by GeekMasher** [comment]
@eidottermihi Thanks for reporting this.

I've run locally some tests and I'm seeing the same issue with `escape-string-regexp` is being reported as both `GPL-3.0 AND MIT`.

It seems to be an issue with how the "extra licensing information" from clearlydefined is being loaded into the checks because when I request the API directly, it says the following:

```
Dependencies :: 762
pkg:npm/escape-string-regexp :: MIT License
```

I'll hopefully have a complete answer and patch ready for you soon.

**Comment by GeekMasher** [comment]
@eidottermihi I found the root cause. The issue with the `ignore` was 2 things, first is that you are using `ids` and not `names`. It is a little confusing the naming but `ids` are for "license ids / names" and `names` is for "dependency names". This is going to be re-named in v3 as multiple people have commented about this before. I will comment [in the PR shortly](https://github.com/it-at-m/appswitcher-vue/pull/74).

The second issue was [a typo in the code](https://github.com/advanced-security/policy-as-code/pull/57/files#diff-4ab62e7bfe032a0d9e697e396311aa75967bcdd00cb6e845be67f146526f6011L346-L349) which pretty much made the ignore list blank every time.

On the subject of the Dependency itself having both GPL and MIT, it seems that this is an issue with the SBOM generated by GitHub. The data in the SBOM, [can download from here](https://github.com/it-at-m/appswitcher-vue/network/dependencies), show both GPL and MIT for v5.0.0

![image](https://github.com/advanced-security/policy-as-code/assets/2772944/7155aec9-097b-4458-8437-5e9fffd8dd21)
*Showing data from SBOM*

I will contact the team to review these dependencies to make sure they are correct or not.

**Comment by GeekMasher** [comment]
That is great, thanks again for reporting this @eidottermihi. Closing issue
